name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [win-x64, linux-x64, osx-arm64]
    env:
      PROJECT_FOLDER: YMouseButtonControl
      PROJECT_NAME: YMouseButtonControl.csproj
      CONFIGURATION: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Execute unit tests
      run: dotnet test

    - name: Restore the application
      run: dotnet restore

    - name: Publish
      run: dotnet publish "${{ env.PROJECT_FOLDER}}/${{ env.PROJECT_NAME }}" -c ${{ env.CONFIGURATION }} -r ${{ matrix.rid }} -p:PublishSingleFile=true -p:SelfContained=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true -p:EnableCompressionInSingleFile=true -p:DebugType=embedded -o bin

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: ${{ matrix.rid }}
        path: bin/
